services:
  postgres:
    image: postgres:16.4
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: t3-app-router
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
