import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { Toaster } from "@/components/ui/sonner";

import { TRPCReactProvider } from "@/trpc/react";
import { ThemeProvider } from "@/components/provider/theme-provider";
import { HydrateClient } from "@/trpc/server";
import SessionProvider from "@/components/provider/session-provider";
import { CheckCircleIcon } from "lucide-react";

export const metadata: Metadata = {
  title: "T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${GeistSans.variable}`}
      suppressHydrationWarning
    >
      <body>
        <TRPCReactProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <HydrateClient>
              <SessionProvider>{children}</SessionProvider>
            </HydrateClient>
          </ThemeProvider>
        </TRPCReactProvider>
        <Toaster
          position="top-center"
          icons={{
            success: <CheckCircleIcon className="size-5" />,
          }}
          richColors
        />
      </body>
    </html>
  );
}
