name: T3 App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npm run build

  test:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "This is a test step"

  integration:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "This is an integration step"

  prod:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "This is a deploy step"
